#!/usr/bin/env bash
# Bring up the dev stack: Wazuh (manager, indexer, dashboard, agent "web01") + ir.mlab.sh,
# wired with the two integrations of this repo. Safe to re-run.
set -euo pipefail
cd "$(dirname "$0")/.."

IR=http://localhost:8080
GEN=dev/.generated
mkdir -p "$GEN/agent-logs" && touch "$GEN"/agent-logs/{auth.log,squid.log,vuln.json}
say() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
envval() { grep -E "^$1=" .env | tail -1 | cut -d= -f2- || true; }

say "Disk"
# Keep 5 GB free on the host no matter what; the images take ~10 GB the first time.
free_gb=$(df -g . | awk 'NR==2 {print $4}')
need=6
docker image inspect wazuh/wazuh-indexer:4.14.8 >/dev/null 2>&1 || need=15
echo "${free_gb} GB free, ${need} GB needed (5 GB kept as margin)"
[ "$free_gb" -ge "$need" ] || { echo "not enough disk, aborting"; exit 1; }

say "Secrets"
[ -n "$(envval MLAB_IR_LI)" ] || { echo "MLAB_IR_LI (ir.mlab.sh licence) missing from .env"; exit 1; }
if [ -z "$(envval INTERNAL_SECRET)" ]; then
  printf '\n# generated by dev/setup.sh (ir.mlab.sh app <-> executor)\nINTERNAL_SECRET=%s\n' "$(openssl rand -hex 32)" >> .env
  echo "INTERNAL_SECRET added to .env"
fi

say "Wazuh certificates"
if [ ! -f dev/wazuh/wazuh_indexer_ssl_certs/root-ca.pem ]; then
  docker compose -f dev/wazuh/generate-indexer-certs.yml run --rm generator || true
  # the generator locks the dir (0500) before its own root-ca-manager copy, and leaves keys 0400:
  # both break on Docker Desktop bind mounts. Dev certs, so open them up.
  certs=dev/wazuh/wazuh_indexer_ssl_certs
  chmod 755 "$certs"
  [ -f "$certs/root-ca-manager.pem" ] || { cp "$certs/root-ca.pem" "$certs/root-ca-manager.pem"; cp "$certs/root-ca.key" "$certs/root-ca-manager.key"; }
  chmod 644 "$certs"/*
  [ -f "$certs/wazuh.manager.pem" ] || { echo "certificate generation failed"; exit 1; }
else
  echo "already generated"
fi

say "ir.mlab.sh"
docker compose up -d ir-app ir-executor
printf 'waiting for %s ' "$IR"
until curl -s -o /dev/null "$IR/"; do printf .; sleep 3; done; echo " up"

if [ ! -s "$GEN/ir_token" ]; then
  jar="$GEN/ir_cookies"
  curl -sf -c "$jar" -H 'Content-Type: application/json' \
    -d '{"email":"admin@localhost","password":"adminadmin"}' "$IR/api/v1/auth/login" > /dev/null
  curl -sf -b "$jar" -H 'Content-Type: application/json' \
    -d '{"note":"wazuh dev stack","kind":"app"}' "$IR/api/v1/user/apikey/create" \
    | python3 -c 'import json,sys,re; print(re.search(r"mlab_app_[0-9A-Za-z]+", json.dumps(json.load(sys.stdin))).group(0))' \
    > "$GEN/ir_token"
  echo "app token created ($GEN/ir_token)"
else
  echo "app token already created"
fi
echo "licence tier: $(docker compose exec -T ir-mysql mysql -N -umlab_web -pchangeme mlabir -e 'SELECT license FROM organizations LIMIT 1' 2>/dev/null)"

say "mlab.sh API key"
if [ -n "$(envval MLAB_API_KEY)" ]; then
  # a bad key is not rejected by mlab.sh, it silently falls back to anonymous quotas: check it
  curl -s -H "Authorization: token $(envval MLAB_API_KEY)" https://mlab.sh/api/v1/ | grep -q '"auth": *"api_key"' \
    && echo "valid ($(curl -s -H "Authorization: token $(envval MLAB_API_KEY)" https://mlab.sh/api/v1/limit/ip | grep -oE '"remaining":[0-9]+' | cut -d: -f2) IP lookups left today)" \
    || { echo "MLAB_API_KEY in .env is not accepted by mlab.sh"; exit 1; }
else
  echo "none in .env: anonymous lookups (IP quota 5/day)"
fi

say "Manager ossec.conf"
sed -e "s|__IR_TOKEN__|$(cat "$GEN/ir_token")|" \
    -e "s|__MLAB_API_KEY__|$(envval MLAB_API_KEY | sed 's/^$/anonymous/')|" \
    dev/wazuh/mlab-integrations.conf \
  | cat <(# vulnerability detection downloads a ~5 GB CVE feed into queue/vd: off for the dev stack
          sed '/<vulnerability-detection>/,/<\/vulnerability-detection>/s|<enabled>yes</enabled>|<enabled>no</enabled>|' \
            dev/wazuh/wazuh_cluster/wazuh_manager.conf) - > "$GEN/ossec.conf"
echo "rendered $GEN/ossec.conf (mlab.sh key: $([ -n "$(envval MLAB_API_KEY)" ] && echo from .env || echo none, anonymous lookups))"

say "Wazuh"
docker compose up -d
# The manager image copies /wazuh-config-mount only when the container is created (not on restart):
# recreate it when any of those files changed. Volumes (agent keys, alerts) are kept.
sum=$(cat "$GEN/ossec.conf" rules/mlab_rules.xml dev/wazuh/{agent.conf,local_internal_options.conf} | shasum | cut -c1-12)
if [ "$sum" != "$(cat "$GEN/manager.sum" 2>/dev/null)" ]; then
  echo "manager config changed, recreating wazuh.manager"
  docker compose up -d --force-recreate wazuh.manager
  echo "$sum" > "$GEN/manager.sum"
fi
agents() { docker compose exec -T wazuh.manager /var/ossec/bin/agent_control -l 2>/dev/null; }
printf 'waiting for agent web01 '
for i in $(seq 60); do
  agents | grep -q 'web01.*Active' && break
  # a recreated agent container lost its key and is refused as a duplicate name: drop the stale entry
  if [ "$i" = 12 ] && stale=$(agents | grep 'Name: web01,' | grep -v Active | grep -oE 'ID: [0-9]+' | grep -oE '[0-9]+'); then
    printf ' (removing stale agent %s) ' "$stale"
    docker compose exec -T wazuh.manager /var/ossec/bin/manage_agents -r "$stale" >/dev/null
  fi
  printf .; sleep 5
done
agents | grep -q 'web01.*Active' && echo " active" || { echo " still not active after 5 min: docker compose logs wazuh.agent"; exit 1; }

cat <<EOF

Stack is up:
  Wazuh dashboard  https://localhost:8443   admin / SecretPassword   (self-signed cert)
  ir.mlab.sh       $IR           admin@localhost / adminadmin
Run the end-to-end checks:  dev/e2e.sh
EOF
